DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CART_ITEM;
DROP TABLE IF EXISTS CART;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS CUSTOMER;
DROP TABLE IF EXISTS SHIPPING_DETAIL;
DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE PRODUCTS (
  ID VARCHAR(25) PRIMARY KEY,
  NAME VARCHAR(50),
  DESCRIPTION VARCHAR(250),
  UNIT_PRICE DECIMAL,
  MANUFACTURER VARCHAR(50),
  CATEGORY VARCHAR(50),
  CONDITION VARCHAR(50),
  UNITS_IN_STOCK BIGINT,
  UNITS_IN_ORDER BIGINT,
  DISCONTINUED BOOLEAN
);

CREATE TABLE CART (
  ID VARCHAR(50) PRIMARY KEY
);

CREATE TABLE CART_ITEM (
  ID VARCHAR(75),
  PRODUCT_ID VARCHAR(25) REFERENCES PRODUCTS(ID),
  CART_ID VARCHAR(50) REFERENCES CART(ID),
  QUANTITY BIGINT,
  CONSTRAINT CART_ITEM_PK PRIMARY KEY (ID,CART_ID)
);

CREATE TABLE ADDRESS (
  ID INTEGER PRIMARY KEY,
  DOOR_NO VARCHAR(25),
  STREET_NAME VARCHAR(25),
  AREA_NAME VARCHAR(25),
  STATE VARCHAR(25),
  COUNTRY VARCHAR(25),
  ZIP VARCHAR(25)
);

CREATE TABLE CUSTOMER (
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(25),
  PHONE_NUMBER VARCHAR(25),
  BILLING_ADDRESS_ID INTEGER REFERENCES ADDRESS(ID)
);

CREATE TABLE SHIPPING_DETAIL (
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(25),
  SHIPPING_DATE VARCHAR(25),
  SHIPPING_ADDRESS_ID INTEGER REFERENCES ADDRESS(ID)
);

CREATE TABLE ORDERS (
  ID SERIAL PRIMARY KEY,
  CART_ID VARCHAR(50) REFERENCES CART(ID),
  CUSTOMER_ID INTEGER REFERENCES CUSTOMER(ID),
  SHIPPING_DETAIL_ID INTEGER REFERENCES SHIPPING_DETAIL(ID)
);