DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS CART_ITEM;
DROP TABLE IF EXISTS CART;

CREATE TABLE PRODUCTS (
  ID VARCHAR(25) PRIMARY KEY,
  NAME VARCHAR(50),
  DESCRIPTION VARCHAR(250),
  UNIT_PRICE DECIMAL,
  MANUFACTURER VARCHAR(50),
  CATEGORY VARCHAR(50),
  CONDITION VARCHAR(50),
  UNITS_IN_STOCK BIGINT,
  UNITS_IN_ORDER BIGINT,
  DISCONTINUED BOOLEAN
);

CREATE TABLE CART (
  ID VARCHAR(50) PRIMARY KEY
);

CREATE TABLE CART_ITEM (
  ID VARCHAR(75),
  PRODUCT_ID VARCHAR(25) REFERENCES PRODUCTS(ID),
  CART_ID VARCHAR(50) REFERENCES CART(ID),
  QUANTITY BIGINT,
  CONSTRAINT CART_ITEM_PK PRIMARY KEY (ID,CART_ID)
);